export const CHROME_TO_TESSERACT = {
  ar: 'ara',
  bg: 'bul',
  bn: 'ben',
  ca: 'cat',
  cs: 'ces',
  da: 'dan',
  de: 'deu',
  el: 'ell',
  en: 'eng',
  'en-GB': 'eng',
  'en-US': 'eng',
  es: 'spa',
  'es-419': 'spa',
  fi: 'fin',
  fr: 'fra',
  'fr-CA': 'fra',
  he: 'heb',
  hi: 'hin',
  hu: 'hun',
  id: 'ind',
  it: 'ita',
  ja: 'jpn',
  ko: 'kor',
  nb: 'nor',
  nl: 'nld',
  no: 'nor',
  pl: 'pol',
  pt: 'por',
  'pt-BR': 'por',
  'pt-PT': 'por',
  ro: 'ron',
  ru: 'rus',
  sv: 'swe',
  th: 'tha',
  tr: 'tur',
  uk: 'ukr',
  vi: 'vie',
  zh: 'chi_sim',
  'zh-CN': 'chi_sim',
  'zh-TW': 'chi_tra',
} as const;

export type ChromeLang = keyof typeof CHROME_TO_TESSERACT;
export type TesseractLang = (typeof CHROME_TO_TESSERACT)[ChromeLang];

export const LANGUAGES_OPTIONS: { value: TesseractLang; label: string }[] = [
  { value: 'ara', label: 'العربية' },
  { value: 'ben', label: 'বাংলা' },
  { value: 'bul', label: 'Български' },
  { value: 'cat', label: 'Català' },
  { value: 'ces', label: 'Čeština' },
  { value: 'chi_sim', label: '简体中文' },
  { value: 'chi_tra', label: '繁體中文' },
  { value: 'dan', label: 'Dansk' },
  { value: 'deu', label: 'Deutsch' },
  { value: 'ell', label: 'Ελληνικά' },
  { value: 'eng', label: 'English' },
  { value: 'fin', label: 'Suomi' },
  { value: 'fra', label: 'Français' },
  { value: 'heb', label: 'עברית' },
  { value: 'hin', label: 'हिन्दी' },
  { value: 'hun', label: 'Magyar' },
  { value: 'ind', label: 'Bahasa Indonesia' },
  { value: 'ita', label: 'Italiano' },
  { value: 'jpn', label: '日本語' },
  { value: 'kor', label: '한국어' },
  { value: 'nld', label: 'Nederlands' },
  { value: 'nor', label: 'Norsk' },
  { value: 'pol', label: 'Polski' },
  { value: 'por', label: 'Português' },
  { value: 'ron', label: 'Română' },
  { value: 'rus', label: 'Русский' },
  { value: 'spa', label: 'Español' },
  { value: 'swe', label: 'Svenska' },
  { value: 'tha', label: 'ไทย' },
  { value: 'tur', label: 'Türkçe' },
  { value: 'ukr', label: 'Українська' },
  { value: 'vie', label: 'Tiếng Việt' },
];
