export const CHROME_TO_TESSERACT = {
  ar: 'ara',
  bg: 'bul',
  bn: 'ben',
  ca: 'cat',
  cs: 'ces',
  da: 'dan',
  de: 'deu',
  el: 'ell',
  en: 'eng',
  'en-GB': 'eng',
  'en-US': 'eng',
  es: 'spa',
  'es-419': 'spa',
  fi: 'fin',
  fr: 'fra',
  'fr-CA': 'fra',
  he: 'heb',
  hi: 'hin',
  hu: 'hun',
  id: 'ind',
  it: 'ita',
  ja: 'jpn',
  ko: 'kor',
  nb: 'nor',
  nl: 'nld',
  no: 'nor',
  pl: 'pol',
  pt: 'por',
  'pt-BR': 'por',
  'pt-PT': 'por',
  ro: 'ron',
  ru: 'rus',
  sv: 'swe',
  th: 'tha',
  tr: 'tur',
  uk: 'ukr',
  vi: 'vie',
  zh: 'chi_sim',
  'zh-CN': 'chi_sim',
  'zh-TW': 'chi_tra',
} as const;

export type ChromeLang = keyof typeof CHROME_TO_TESSERACT;
export type TesseractLang = (typeof CHROME_TO_TESSERACT)[ChromeLang];

export interface LanguageSchema {
  label: string;
  island: {
    croppedScreenshot: string;
    processing: string;
    expand: string;
    copied: string;
    extracted: string;
    error: string;
    noText: string;
    clipboardError: string;
    lang: string;
    autoCopy: string;
    autoExpand: string;
    shortcut: string;
    setShortcut: string;
  };
  backup: {
    tabName: string;
    screenshot: string;
    banner: string;
  };
}

export const LANGUAGES: Record<TesseractLang, LanguageSchema> = {
  eng: {
    label: 'English',
    island: {
      croppedScreenshot: 'Captured region',
      processing: 'processing',
      expand: 'Click to expand',
      copied: 'Copied!',
      extracted: 'Extracted',
      error: 'Error',
      noText: 'No text',
      clipboardError: 'Clipboard Error',
      lang: 'Language',
      autoCopy: 'Auto-Copy',
      autoExpand: 'Auto-Expand',
      shortcut: 'Keyboard shortcut',
      setShortcut: 'Set shortcut',
    },
    backup: {
      tabName: 'Screenshot of original tab',
      screenshot: 'screenshot',
      banner: 'Original tab was protected. Using read-only screenshot.',
    },
  },
  vie: {
    label: 'Tiếng Việt',
    island: {
      croppedScreenshot: 'Ảnh chọn',
      processing: 'Đang xử lý...',
      expand: 'Mở rộng',
      copied: 'Đã sao chép!',
      extracted: 'Đã trích xuất',
      error: 'Lỗi',
      noText: 'Trống',
      lang: 'Ngôn ngữ',
      clipboardError: 'Lỗi bộ nhớ tạm',
      autoCopy: 'Tự động-sao chép',
      autoExpand: 'Tự động-mở rộng',
      shortcut: 'Phím tắt',
      setShortcut: 'Cài đặt phím tắt',
    },
    backup: {
      tabName: 'Ảnh chụp trang gốc',
      screenshot: 'Ảnh chụp',
      banner: 'Trang gốc được bảo mật. Dùng ảnh chụp màn hình.',
    },
  },
  ara: {
    label: 'العربية',
    island: {
      croppedScreenshot: 'المنطقة الملتقطة',
      processing: 'جارٍ المعالجة...',
      expand: 'انقر للتوسيع',
      copied: 'تم النسخ!',
      extracted: 'تم الاستخراج',
      error: 'خطأ',
      noText: 'لا يوجد نص',
      clipboardError: 'خطأ في الحافظة',
      lang: 'لغة',
      autoCopy: 'نسخ تلقائي',
      autoExpand: 'توسيع تلقائي',
      shortcut: 'اختصار لوحة المفاتيح',
      setShortcut: 'تعيين اختصار',
    },
    backup: {
      tabName: 'لقطة شاشة لعلامة التبويب الأصلية',
      screenshot: 'لقطة شاشة',
      banner: 'علامة التبويب الأصلية محمية. استخدام لقطة شاشة للقراءة فقط.',
    },
  },
  bul: {
    label: 'Български',
    island: {
      croppedScreenshot: 'Заснета област',
      processing: 'обработка...',
      expand: 'Кликнете за разширяване',
      copied: 'Копирано!',
      extracted: 'Извлечено',
      error: 'Грешка',
      noText: 'Няма текст',
      clipboardError: 'Грешка в клипборда',
      lang: 'Език',
      autoCopy: 'Авто-копиране',
      autoExpand: 'Авто-разширяване',
      shortcut: 'Клавишна комбинация',
      setShortcut: 'Задаване на пряк път',
    },
    backup: {
      tabName: 'Снимка на оригиналния раздел',
      screenshot: 'снимка на екрана',
      banner:
        'Оригиналният раздел беше защитен. Използване на снимка само за четене.',
    },
  },
  ben: {
    label: 'বাংলা',
    island: {
      croppedScreenshot: 'ক্যাপচার করা এলাকা',
      processing: 'প্রক্রিয়াধীন...',
      expand: 'প্রসারিত করতে ক্লিক করুন',
      copied: 'অনুলিপি করা হয়েছে!',
      extracted: 'নিষ্কাশিত',
      error: 'ত্রুটি',
      noText: 'কোন পাঠ্য নেই',
      clipboardError: 'ক্লিপবোর্ড ত্রুটি',
      lang: 'ভাষা',
      autoCopy: 'স্বয়ংক্রিয় অনুলিপি',
      autoExpand: 'স্বয়ংক্রিয় প্রসারিত',
      shortcut: 'কীবোর্ড শর্টকাট',
      setShortcut: 'শর্টকাট সেট করুন',
    },
    backup: {
      tabName: 'মূল ট্যাবের স্ক্রিনশট',
      screenshot: 'স্ক্রিনশট',
      banner:
        'মূল ট্যাব সুরক্ষিত ছিল। শুধুমাত্র পাঠযোগ্য স্ক্রিনশট ব্যবহার করা হচ্ছে।',
    },
  },
  cat: {
    label: 'Català',
    island: {
      croppedScreenshot: 'Regió capturada',
      processing: 'processant...',
      expand: 'Clica per expandir',
      copied: 'Copiat!',
      extracted: 'Extret',
      error: 'Error',
      noText: 'Sense text',
      clipboardError: 'Error del porta-retalls',
      lang: 'Idioma',
      autoCopy: 'Còpia automàtica',
      autoExpand: 'Expansió automàtica',
      shortcut: 'Drecera de teclat',
      setShortcut: 'Configura drecera',
    },
    backup: {
      tabName: 'Captura de la pestanya original',
      screenshot: 'captura de pantalla',
      banner:
        "La pestanya original estava protegida. S'utilitza una captura de només lectura.",
    },
  },
  ces: {
    label: 'Čeština',
    island: {
      croppedScreenshot: 'Zachycená oblast',
      processing: 'zpracování...',
      expand: 'Kliknutím rozbalíte',
      copied: 'Zkopírováno!',
      extracted: 'Vyjmuto',
      error: 'Chyba',
      noText: 'Žádný text',
      clipboardError: 'Chyba schránky',
      lang: 'Jazyk',
      autoCopy: 'Auto-kopírování',
      autoExpand: 'Auto-rozbalení',
      shortcut: 'Klávesová zkratka',
      setShortcut: 'Nastavit zkratku',
    },
    backup: {
      tabName: 'Snímek původní karty',
      screenshot: 'snímek obrazovky',
      banner: 'Původní karta byla chráněna. Používá se snímek pouze pro čtení.',
    },
  },
  dan: {
    label: 'Dansk',
    island: {
      croppedScreenshot: 'Fanget område',
      processing: 'behandler...',
      expand: 'Klik for at udvide',
      copied: 'Kopieret!',
      extracted: 'Udtrukket',
      error: 'Fejl',
      noText: 'Ingen tekst',
      clipboardError: 'Udklipsholderfejl',
      lang: 'Sprog',
      autoCopy: 'Auto-kopi',
      autoExpand: 'Auto-udvid',
      shortcut: 'Tastaturgenvej',
      setShortcut: 'Indstil genvej',
    },
    backup: {
      tabName: 'Skærmbillede af oprindelig fane',
      screenshot: 'skærmbillede',
      banner:
        'Den oprindelige fane var beskyttet. Bruger skrivebeskyttet skærmbillede.',
    },
  },
  deu: {
    label: 'Deutsch',
    island: {
      croppedScreenshot: 'Erfasster Bereich',
      processing: 'wird verarbeitet...',
      expand: 'Zum Erweitern klicken',
      copied: 'Kopiert!',
      extracted: 'Extrahiert',
      error: 'Fehler',
      noText: 'Kein Text',
      clipboardError: 'Zwischenablage-Fehler',
      lang: 'Sprache',
      autoCopy: 'Auto-Kopie',
      autoExpand: 'Auto-Erweitern',
      shortcut: 'Tastenkürzel',
      setShortcut: 'Kürzel festlegen',
    },
    backup: {
      tabName: 'Screenshot des Original-Tabs',
      screenshot: 'Screenshot',
      banner:
        'Original-Tab war geschützt. Schreibgeschützter Screenshot wird verwendet.',
    },
  },
  ell: {
    label: 'Ελληνικά',
    island: {
      croppedScreenshot: 'Καταγεγραμμένη περιοχή',
      processing: 'επεξεργασία...',
      expand: 'Κλικ για επέκταση',
      copied: 'Αντιγράφηκε!',
      extracted: 'Εξήχθη',
      error: 'Σφάλμα',
      noText: 'Χωρίς κείμενο',
      clipboardError: 'Σφάλμα προχείρου',
      lang: 'Γλώσσα',
      autoCopy: 'Αυτόματη αντιγραφή',
      autoExpand: 'Αυτόματη επέκταση',
      shortcut: 'Συντόμευση πληκτρολογίου',
      setShortcut: 'Ορισμός συντόμευσης',
    },
    backup: {
      tabName: 'Στιγμιότυπο αρχικής καρτέλας',
      screenshot: 'στιγμιότυπο',
      banner:
        'Η αρχική καρτέλα ήταν προστατευμένη. Χρήση στιγμιότυπου μόνο για ανάγνωση.',
    },
  },
  spa: {
    label: 'Español',
    island: {
      croppedScreenshot: 'Región capturada',
      processing: 'procesando...',
      expand: 'Clic para expandir',
      copied: '¡Copiado!',
      extracted: 'Extraído',
      error: 'Error',
      noText: 'Sin texto',
      clipboardError: 'Error del portapapeles',
      lang: 'Idioma',
      autoCopy: 'Auto-copia',
      autoExpand: 'Auto-expansión',
      shortcut: 'Atajo de teclado',
      setShortcut: 'Configurar atajo',
    },
    backup: {
      tabName: 'Captura de la pestaña original',
      screenshot: 'captura de pantalla',
      banner:
        'La pestaña original estaba protegida. Usando captura de solo lectura.',
    },
  },
  fin: {
    label: 'Suomi',
    island: {
      croppedScreenshot: 'Kaapattu alue',
      processing: 'käsitellään...',
      expand: 'Laajenna napsauttamalla',
      copied: 'Kopioitu!',
      extracted: 'Poimittu',
      error: 'Virhe',
      noText: 'Ei tekstiä',
      clipboardError: 'Leikepöytävirhe',
      lang: 'Kieli',
      autoCopy: 'Automaattinen kopiointi',
      autoExpand: 'Automaattinen laajennus',
      shortcut: 'Pikanäppäin',
      setShortcut: 'Aseta pikanäppäin',
    },
    backup: {
      tabName: 'Kuvakaappaus alkuperäisestä välilehdestä',
      screenshot: 'kuvakaappaus',
      banner:
        'Alkuperäinen välilehti oli suojattu. Käytetään vain luku -kuvakaappausta.',
    },
  },
  fra: {
    label: 'Français',
    island: {
      croppedScreenshot: 'Zone capturée',
      processing: 'traitement...',
      expand: 'Cliquer pour agrandir',
      copied: 'Copié !',
      extracted: 'Extrait',
      error: 'Erreur',
      noText: 'Aucun texte',
      clipboardError: 'Erreur presse-papiers',
      lang: 'Langue',
      autoCopy: 'Copie auto',
      autoExpand: 'Extension auto',
      shortcut: 'Raccourci clavier',
      setShortcut: 'Définir raccourci',
    },
    backup: {
      tabName: "Capture de l'onglet original",
      screenshot: "capture d'écran",
      banner:
        "L'onglet original était protégé. Utilisation d'une capture en lecture seule.",
    },
  },
  heb: {
    label: 'עברית',
    island: {
      croppedScreenshot: 'אזור שנלכד',
      processing: 'מעבד...',
      expand: 'לחץ להרחבה',
      copied: 'הועתק!',
      extracted: 'חולץ',
      error: 'שגיאה',
      noText: 'אין טקסט',
      clipboardError: 'שגיאת לוח',
      lang: 'שפה',
      autoCopy: 'העתקה אוטומטית',
      autoExpand: 'הרחבה אוטומטית',
      shortcut: 'קיצור מקלדת',
      setShortcut: 'הגדר קיצור דרך',
    },
    backup: {
      tabName: 'צילום מסך של הכרטיסייה המקורית',
      screenshot: 'צילום מסך',
      banner: 'הכרטיסייה המקורית הייתה מוגנת. משתמש בצילום מסך לקריאה בלבד.',
    },
  },
  hin: {
    label: 'हिन्दी',
    island: {
      croppedScreenshot: 'कैप्चर किया गया क्षेत्र',
      processing: 'प्रक्रिया जारी है...',
      expand: 'विस्तार करने के लिए क्लिक करें',
      copied: 'कॉपी किया गया!',
      extracted: 'निकाला गया',
      error: 'त्रुटि',
      noText: 'कोई पाठ नहीं',
      clipboardError: 'क्लिपबोर्ड त्रुटि',
      lang: 'भाषा',
      autoCopy: 'ऑटो-कॉपी',
      autoExpand: 'ऑटो-विस्तार',
      shortcut: 'कीबोर्ड शॉर्टकट',
      setShortcut: 'शॉर्टकट सेट करें',
    },
    backup: {
      tabName: 'मूल टैब का स्क्रीनशॉट',
      screenshot: 'स्क्रीनशॉट',
      banner:
        'मूल टैब सुरक्षित था। केवल पढ़ने योग्य स्क्रीनशॉट का उपयोग कर रहा है।',
    },
  },
  hun: {
    label: 'Magyar',
    island: {
      croppedScreenshot: 'Rögzített terület',
      processing: 'feldolgozás...',
      expand: 'Kattintson a kibontáshoz',
      copied: 'Másolva!',
      extracted: 'Kinyerve',
      error: 'Hiba',
      noText: 'Nincs szöveg',
      clipboardError: 'Vágólap hiba',
      lang: 'Nyelv',
      autoCopy: 'Auto-másolás',
      autoExpand: 'Auto-kibontás',
      shortcut: 'Billentyűparancs',
      setShortcut: 'Parancs beállítása',
    },
    backup: {
      tabName: 'Képernyőkép az eredeti lapról',
      screenshot: 'képernyőkép',
      banner:
        'Az eredeti lap védett volt. Csak olvasható képernyőkép használata.',
    },
  },
  ind: {
    label: 'Bahasa Indonesia',
    island: {
      croppedScreenshot: 'Area yang ditangkap',
      processing: 'memproses...',
      expand: 'Klik untuk memperluas',
      copied: 'Disalin!',
      extracted: 'Diekstrak',
      error: 'Kesalahan',
      noText: 'Tidak ada teks',
      clipboardError: 'Kesalahan Papan Klip',
      lang: 'Bahasa',
      autoCopy: 'Salin-Otomatis',
      autoExpand: 'Perluas-Otomatis',
      shortcut: 'Pintasan keyboard',
      setShortcut: 'Atur pintasan',
    },
    backup: {
      tabName: 'Tangkapan layar tab asli',
      screenshot: 'tangkapan layar',
      banner: 'Tab asli dilindungi. Menggunakan tangkapan layar baca-saja.',
    },
  },
  ita: {
    label: 'Italiano',
    island: {
      croppedScreenshot: 'Area catturata',
      processing: 'elaborazione...',
      expand: 'Clicca per espandere',
      copied: 'Copiato!',
      extracted: 'Estratto',
      error: 'Errore',
      noText: 'Nessun testo',
      clipboardError: 'Errore appunti',
      lang: 'Lingua',
      autoCopy: 'Copia automatica',
      autoExpand: 'Espansione automatica',
      shortcut: 'Scorciatoia da tastiera',
      setShortcut: 'Imposta scorciatoia',
    },
    backup: {
      tabName: 'Screenshot della scheda originale',
      screenshot: 'screenshot',
      banner:
        'La scheda originale era protetta. Uso screenshot di sola lettura.',
    },
  },
  jpn: {
    label: '日本語',
    island: {
      croppedScreenshot: 'キャプチャ領域',
      processing: '処理中...',
      expand: 'クリックして展開',
      copied: 'コピーしました！',
      extracted: '抽出完了',
      error: 'エラー',
      noText: 'テキストなし',
      clipboardError: 'クリップボードエラー',
      lang: '言語',
      autoCopy: '自動コピー',
      autoExpand: '自動展開',
      shortcut: 'キーボードショートカット',
      setShortcut: 'ショートカット設定',
    },
    backup: {
      tabName: '元のタブのスクリーンショット',
      screenshot: 'スクリーンショット',
      banner:
        '元のタブは保護されていました。読み取り専用のスクリーンショットを使用します。',
    },
  },
  kor: {
    label: '한국어',
    island: {
      croppedScreenshot: '캡처된 영역',
      processing: '처리 중...',
      expand: '클릭하여 확장',
      copied: '복사됨!',
      extracted: '추출됨',
      error: '오류',
      noText: '텍스트 없음',
      clipboardError: '클립보드 오류',
      lang: '언어',
      autoCopy: '자동 복사',
      autoExpand: '자동 확장',
      shortcut: '키보드 단축키',
      setShortcut: '단축키 설정',
    },
    backup: {
      tabName: '원본 탭의 스크린샷',
      screenshot: '스크린샷',
      banner: '원본 탭이 보호되었습니다. 읽기 전용 스크린샷을 사용합니다。',
    },
  },
  nor: {
    label: 'Norsk',
    island: {
      croppedScreenshot: 'Fanget område',
      processing: 'behandler...',
      expand: 'Klikk for å utvide',
      copied: 'Kopiert!',
      extracted: 'Trukket ut',
      error: 'Feil',
      noText: 'Ingen tekst',
      clipboardError: 'Utklippstavlefeil',
      lang: 'Språk',
      autoCopy: 'Auto-kopi',
      autoExpand: 'Auto-utvid',
      shortcut: 'Tastatursnarvei',
      setShortcut: 'Angi snarvei',
    },
    backup: {
      tabName: 'Skjermbilde av original fane',
      screenshot: 'skjermbilde',
      banner:
        'Den originale fanen var beskyttet. Bruker skrivebeskyttet skjermbilde.',
    },
  },
  nld: {
    label: 'Nederlands',
    island: {
      croppedScreenshot: 'Vastgelegd gebied',
      processing: 'verwerken...',
      expand: 'Klik om uit te breiden',
      copied: 'Gekopieerd!',
      extracted: 'Geëxtraheerd',
      error: 'Fout',
      noText: 'Geen tekst',
      clipboardError: 'Klembordfout',
      lang: 'Taal',
      autoCopy: 'Auto-kopiëren',
      autoExpand: 'Auto-uitbreiden',
      shortcut: 'Sneltoets',
      setShortcut: 'Sneltoets instellen',
    },
    backup: {
      tabName: 'Screenshot van origineel tabblad',
      screenshot: 'screenshot',
      banner:
        'Het originele tabblad was beveiligd. Alleen-lezen screenshot wordt gebruikt.',
    },
  },
  pol: {
    label: 'Polski',
    island: {
      croppedScreenshot: 'Przechwycony obszar',
      processing: 'przetwarzanie...',
      expand: 'Kliknij, aby rozwinąć',
      copied: 'Skopiowano!',
      extracted: 'Wyodrębniono',
      error: 'Błąd',
      noText: 'Brak tekstu',
      clipboardError: 'Błąd schowka',
      lang: 'Język',
      autoCopy: 'Auto-kopiowanie',
      autoExpand: 'Auto-rozwijanie',
      shortcut: 'Skrót klawiszowy',
      setShortcut: 'Ustaw skrót',
    },
    backup: {
      tabName: 'Zrzut ekranu oryginalnej karty',
      screenshot: 'zrzut ekranu',
      banner:
        'Oryginalna karta była chroniona. Używanie zrzutu ekranu tylko do odczytu.',
    },
  },
  por: {
    label: 'Português',
    island: {
      croppedScreenshot: 'Região capturada',
      processing: 'processando...',
      expand: 'Clique para expandir',
      copied: 'Copiado!',
      extracted: 'Extraído',
      error: 'Erro',
      noText: 'Sem texto',
      clipboardError: 'Erro na área de transferência',
      lang: 'Idioma',
      autoCopy: 'Cópia automática',
      autoExpand: 'Expansão automática',
      shortcut: 'Atalho de teclado',
      setShortcut: 'Definir atalho',
    },
    backup: {
      tabName: 'Captura da aba original',
      screenshot: 'captura de tela',
      banner:
        'A aba original estava protegida. Usando captura somente leitura.',
    },
  },
  ron: {
    label: 'Română',
    island: {
      croppedScreenshot: 'Regiune capturată',
      processing: 'se procesează...',
      expand: 'Click pentru extindere',
      copied: 'Copiat!',
      extracted: 'Extras',
      error: 'Eroare',
      noText: 'Fără text',
      clipboardError: 'Eroare clipboard',
      lang: 'Limbă',
      autoCopy: 'Auto-copiere',
      autoExpand: 'Auto-extindere',
      shortcut: 'Scurtătură tastatură',
      setShortcut: 'Setare scurtătură',
    },
    backup: {
      tabName: 'Captură de ecran a filei originale',
      screenshot: 'captură de ecran',
      banner:
        'Fila originală a fost protejată. Se utilizează captură doar pentru citire.',
    },
  },
  rus: {
    label: 'Русский',
    island: {
      croppedScreenshot: 'Захваченная область',
      processing: 'обработка...',
      expand: 'Нажмите, чтобы развернуть',
      copied: 'Скопировано!',
      extracted: 'Извлечено',
      error: 'Ошибка',
      noText: 'Нет текста',
      clipboardError: 'Ошибка буфера обмена',
      lang: 'Язык',
      autoCopy: 'Авто-копирование',
      autoExpand: 'Авто-развертывание',
      shortcut: 'Сочетание клавиш',
      setShortcut: 'Задать сочетание',
    },
    backup: {
      tabName: 'Скриншот исходной вкладки',
      screenshot: 'скриншот',
      banner:
        'Исходная вкладка была защищена. Используется скриншот только для чтения.',
    },
  },
  swe: {
    label: 'Svenska',
    island: {
      croppedScreenshot: 'Fångat område',
      processing: 'bearbetar...',
      expand: 'Klicka för att expandera',
      copied: 'Kopierat!',
      extracted: 'Extraherat',
      error: 'Fel',
      noText: 'Ingen text',
      clipboardError: 'Urklippsfel',
      lang: 'Språk',
      autoCopy: 'Auto-kopiera',
      autoExpand: 'Auto-expandera',
      shortcut: 'Kortkommando',
      setShortcut: 'Ange genväg',
    },
    backup: {
      tabName: 'Skärmdump av ursprunglig flik',
      screenshot: 'skärmdump',
      banner:
        'Den ursprungliga fliken var skyddad. Använder skrivskyddad skärmdump.',
    },
  },
  tha: {
    label: 'ไทย',
    island: {
      croppedScreenshot: 'พื้นที่ที่จับภาพ',
      processing: 'กำลังประมวลผล...',
      expand: 'คลิกเพื่อขยาย',
      copied: 'คัดลอกแล้ว!',
      extracted: 'สกัดแล้ว',
      error: 'ข้อผิดพลาด',
      noText: 'ไม่มีข้อความ',
      clipboardError: 'ข้อผิดพลาดคลิปบอร์ด',
      lang: 'ภาษา',
      autoCopy: 'คัดลอกอัตโนมัติ',
      autoExpand: 'ขยายอัตโนมัติ',
      shortcut: 'แป้นพิมพ์ลัด',
      setShortcut: 'ตั้งค่าทางลัด',
    },
    backup: {
      tabName: 'ภาพหน้าจอของแท็บเดิม',
      screenshot: 'ภาพหน้าจอ',
      banner: 'แท็บเดิมได้รับการป้องกัน กำลังใช้ภาพหน้าจอแบบอ่านอย่างเดียว',
    },
  },
  tur: {
    label: 'Türkçe',
    island: {
      croppedScreenshot: 'Yakalanan bölge',
      processing: 'işleniyor...',
      expand: 'Genişletmek için tıkla',
      copied: 'Kopyalandı!',
      extracted: 'Çıkarıldı',
      error: 'Hata',
      noText: 'Metin yok',
      clipboardError: 'Pano Hatası',
      lang: 'Dil',
      autoCopy: 'Otomatik Kopyala',
      autoExpand: 'Otomatik Genişlet',
      shortcut: 'Klavye kısayolu',
      setShortcut: 'Kısayol ayarla',
    },
    backup: {
      tabName: 'Orijinal sekmenin ekran görüntüsü',
      screenshot: 'ekran görüntüsü',
      banner:
        'Orijinal sekme korumalıydı. Salt okunur ekran görüntüsü kullanılıyor.',
    },
  },
  ukr: {
    label: 'Українська',
    island: {
      croppedScreenshot: 'Захоплена область',
      processing: 'обробка...',
      expand: 'Натисніть, щоб розгорнути',
      copied: 'Скопійовано!',
      extracted: 'Витягнуто',
      error: 'Помилка',
      noText: 'Немає тексту',
      clipboardError: 'Помилка буфера обміну',
      lang: 'Мова',
      autoCopy: 'Авто-копіювання',
      autoExpand: 'Авто-розгортання',
      shortcut: 'Комбінація клавіш',
      setShortcut: 'Встановити ярлик',
    },
    backup: {
      tabName: 'Скріншот оригінальної вкладки',
      screenshot: 'скріншот',
      banner:
        'Оригінальна вкладка була захищена. Використовується скріншот лише для читання.',
    },
  },
  chi_sim: {
    label: '简体中文',
    island: {
      croppedScreenshot: '截图区域',
      processing: '处理中...',
      expand: '点击展开',
      copied: '已复制！',
      extracted: '已提取',
      error: '错误',
      noText: '无文本',
      clipboardError: '剪贴板错误',
      lang: '语言',
      autoCopy: '自动复制',
      autoExpand: '自动展开',
      shortcut: '键盘快捷键',
      setShortcut: '设置快捷键',
    },
    backup: {
      tabName: '原标签页截图',
      screenshot: '截图',
      banner: '原标签页受保护。正在使用只读截图。',
    },
  },
  chi_tra: {
    label: '繁體中文',
    island: {
      croppedScreenshot: '截圖區域',
      processing: '處理中...',
      expand: '點擊展開',
      copied: '已複製！',
      extracted: '已提取',
      error: '錯誤',
      noText: '無文字',
      clipboardError: '剪貼簿錯誤',
      lang: '語言',
      autoCopy: '自動複製',
      autoExpand: '自動展開',
      shortcut: '鍵盤快捷鍵',
      setShortcut: '設定快捷鍵',
    },
    backup: {
      tabName: '原分頁截圖',
      screenshot: '截圖',
      banner: '原分頁受保護。正在使用唯讀截圖。',
    },
  },
} as const;

export const LANGUAGES_OPTIONS = Object.entries(LANGUAGES).map(
  ([key, data]) => ({
    value: key,
    label: data.label,
  })
);
